name: Awesome Lint Check

on:
  push:
    branches: [ "master" ]
    paths:
      - 'README.md'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'README.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install awesome-lint
        run: npm install -g awesome-lint

      - name: Run awesome-lint
        run: |
          awesome-lint . > output.log 2>&1 || true
          cat output.log

      - name: Check for success message
        run: |
          if grep -q "✔ Linting" output.log; then
            echo "✅ Awesome lint passed!"
          else
            echo "❌ Awesome lint failed!"
            exit 1
          fi
